name: C Gift Card Reader CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: make Makefile
      run: make Makefile
      
    - name: test infinite loop hang gift card
      run: gcc giftcardreader2.c -o  giftcardreader && ./giftcardreader 1 hang.gft
      
      
      
