name: C Gift Card Reader CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: make Makefile
      run: make Makefile
      
      
      
