name: C Gift Card Reader CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: make Makefile
      run: make part2/Makefile
      
    - name: test infinite loop hang gift card
      run: gcc part2/giftcardreader2.c -o  giftcardreader && ./giftcardreader 1 part2/hang.gft
      
      
      
