name: C Gift Card Reader CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
      
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      
    - name: make Makefile
      run: make Makefile
      
      
      
